all:
	g++ -o dataGen dataGen.cpp
	g++ -o createIndexes createIndexes.cpp
	g++ -o binTreesIndex binTreesIndex.cpp
	g++ -o bplusTree bplusTree.cpp
	g++ -o createAndSaveTreeIndexes createAndSaveTreeIndexes.cpp
	g++ -o readTreeIndexes readTreeIndexes.cpp
	g++ -o runTreeFiles runTreeFiles.cpp 
	g++ -o  spaceCount spaceCount.cpp
clean:
	rm dataGen createIndexes binTreesIndex readTreeIndexes createAndSaveTreeIndexes bplusTree runTreeFiles spaceCount
